name: Laravel CI

on:
  push:
    branches: [ "main", "master", "development" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_sqlite, zip, exif, pcntl, bcmath
        ini-values: post_max_size=256M, upload_max_filesize=256M
        tools: composer

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-interaction --optimize-autoloader
      working-directory: ./src/

    - name: Create .env file
      run: cp .env.example .env
      working-directory: ./src/

    - name: Generate Application Key
      run: php artisan key:generate
      working-directory: ./src/
